spring:
  application:
    name: dionomy-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/dionomy
    username: dionomy
    password: dionomy
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
