spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dionomy
    username: dionomy
    password: dionomy
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
