spring:
  datasource:
    url: ${DIONOMY_DATABASE_URL}
    username: ${DIONOMY_DATABASE_USERNAME}
    password: ${DIONOMY_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
